Settings: check resource exists to accommodate zip archives
When pkg_resources.resource_filename() is used within a zip file
(egg or wheel), it will raise an exception if the resource does
not exist, like:

   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1145, in resource_filename
       self, resource_name
     File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1744, in get_resource_filename
       return self._extract_resource(manager, zip_path)
     File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1765, in _extract_resource
       timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
   KeyError: 'avocado/etc/avocado/avocado.conf

To avoid a crash, let's verify if the resource exists and only attempt
to get the resource and read it if it exists.

Signed-off-by: Cleber Rosa <crosa@redhat.com>